### ISSUE TITLE
sql.js should support REGEXP

### ISSUE THREAD

**Issue by jasonbaker** [kripken/sql.js#101]
What would be really nice is if there were built-in support for regexps. The most straightforward way to do that would likely be to make the REGEXP operator work with javascript regular expressions.

**Comment by lovasoa** [comment]
This is just an example  of custom function, implrmented in #95.

**Comment by jasonbaker** [comment]
I suppose what I'm asking for is a sane default then. It would be nice to have a built-in default that just used javascript regexps. I would suspect that would work for 90% of users of sql.js.
