### ISSUE TITLE
Can't use sql.js inside pure html on loca file disk

### ISSUE THREAD

**Issue by henryfelipe** [kripken/sql.js#102]
Hello. I'm trying to use the api sql.js, referenced it into my html (pure html with javascript). But when I call the first line of code "//Create the database: var db = new SQL.Database();", browser says that SQL is not defined.

How to use it? I need to call some init function/procedure before use any of that methods?

Thanks,

Henry Felipe

**Comment by lovasoa** [comment]
You must not have included the `sql.js` file correctly.

**Comment by lovasoa** [comment]
```javascript
<script src='path/to/sql.js'></script>
```
