### ISSUE TITLE
Global access to a database

### ISSUE THREAD

**Issue by anandagowdan3** [kripken/sql.js#104]
How can i make database session scoped in browser and access database across different pages ?

**Comment by lovasoa** [comment]
I would recommend you to use a [SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) for that purpose. You open a database in the worker, and the different applications communicate with that worker.

But this is something you have to do in your application, not something that should be implemented in `sql.js`.

**Comment by anandagowdan3** [comment]
Thank you so much @lovasoa.
