### ISSUE TITLE
store and retrieve database from local filesystem.

### ISSUE THREAD

**Issue by anandagowdan3** [kripken/sql.js#107]
I'm working with client side storage with sql.js. Having to work with huge amounts of data, i'm looking for ways to store database into a file at clients local system and retrieve. Are there any libraries other than node.js which work with sql.js.?

**Comment by lovasoa** [comment]
If you work with huge amounts of data, then you'd better not use sql.js. This question has been answered multiple times. Please take a look at closed issues, at the wiki, and at the README.
