### ISSUE TITLE
Hybrid Android app?

### ISSUE THREAD

**Issue by KeiKun11** [kripken/sql.js#109]
Is possible use sql.js in Hybrid Android app? If is possible, What is the code to load that bd? I tried the different codes here but... I can't load it....

**Comment by lovasoa** [comment]
sql.js is a normal js library. You should read the documenation of whatever framework you are using to build your "Hybrid Android App" about how to include a js library.

**Comment by KeiKun11** [comment]
I've seen the documentation of this library and I've tried all the existing code and any code gets load the database offline.

The most similar code would be as follows, but does not work to load a local database.

```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET', '/path/to/database.sqlite', true);
xhr.responseType = 'arraybuffer';

xhr.onload = function(e) {
  var uInt8Array = new Uint8Array(this.response);
  var db = new SQL.Database(uInt8Array);
  var contents = db.exec("SELECT * FROM my_table");
  // contents is now [{columns:['col1','col2',...], values:[[first row], [second row], ...]}]
};
xhr.send();
```

**Comment by KeiKun11** [comment]
I'm going to use an interface in java to talk with the javascipt.

**Comment by lovasoa** [comment]
If you write java code, then why don't you just use android's apis?

**Comment by KeiKun11** [comment]
Because I need HTML5+CSS+JavaScript in one part of my app.

**Comment by lovasoa** [comment]
Then you should use whatever native the framework you use has.
For instance, if you use cordova, there is :
https://github.com/litehelpers/Cordova-sqlite-storage

2015-06-10 17:07 GMT+02:00 KeiKun11 <notifications@github.com>:
