### ISSUE TITLE
persistance of db

### ISSUE THREAD

**Issue by rjv94rnjn** [kripken/sql.js#110]
How to keep data stable in db till it is not deleted programmatically means as per user need even after browser is closed and changing pages.Please,suggest me.....

**Comment by kapila93** [comment]
https://github.com/kripken/sql.js/wiki/Persisting-a-Modified-Database

This works as long as it's not a limited DOM environment (HTML5 Canvas etc).

**Comment by dinedal** [comment]
Thanks @kapila93 

Closing as resolved.
