### ISSUE TITLE
Writing a simple INSERT

### ISSUE THREAD

**Issue by coryjg** [kripken/sql.js#111]
I'm trying to do a simple insert and for some reason it's not working.  I can query my SQLite db all day long with SELECT statements so I know the connection is fine and can see the table.  When I try running the INSERT statement it runs through the code with no error messages, which is even more frustrating.  Modifying my INSERT string will produce errors if not formatted correctly, so I think that is sound.  It feels like there should be a commit or something after doing an insert but your demos don't mention that (As you can see, I pulled most of my logic from your demos). Any suggestions would be appreciated.  

 var xhr = new XMLHttpRequest();
        xhr.open('POST', '../database/DSBEA.db', true);
        xhr.responseType = 'arraybuffer';

```
    xhr.onload = function (e) {
        var uInt8Array = new Uint8Array(this.response);
        var db = new SQL.Database(uInt8Array);

        //Reading from DB - returns correct row from my table.
        var contents1 = db.exec("SELECT * FROM Role WHERE priority = 3 ");
        //Trying to do an INSERT - no error is thrown
        var addRoleData = "INSERT INTO Role (crew_group, role, priority) VALUES ('MEDICAL','Role 1',5)";
       db.run(addRoleData);
       //I also tried doing a db.exec, no luck.
```

 };
        xhr.send();

**Comment by lovasoa** [comment]
What do you mean by "doesn't work" ? Of course it doesn't insert the data in the database that lies in your server. Client-side code can't change a file on your server if you don't add some server-side logic.


Before using sql.js, you should make sure to understand how it works, and what it can do. 

Sql.js is SQLite compiled to JavaScript. It opens a file *in memory*, and doesn't have any options to save the database anywhere. The only thing you can do is export the modified database file as a byte array. Then, it's up to you to decide what you do with this array. You could send it to the server, or petsist it on the client. But YOU have to write the code to do so.

**Comment by coryjg** [comment]
Ahh I see now.  I was under the impression that I was creating a connection straight to my .db and had the ability to manipulate it.  The examples shown gave me the impression you could just create a SQL string and execute it and it would affect the db directly.

**Comment by dinedal** [comment]
Closing as resolved.
