### ISSUE TITLE
How do I build this without `eval()`?

### ISSUE THREAD

**Issue by SunboX** [kripken/sql.js#118]
Hi, I'm getting a CSP warning using Firefox OS. I've no experience with Emscripten. How do I compile `sql.js` so it doesn't use `eval()` inside? Or is there a already compile version somewhere?

**Comment by lovasoa** [comment]
This issue has already been discussed in #71 and #97.

Either ignore the warning (it's safe), or build sql.js with `-s NO_DYNAMIC_EXECUTION=1`.

**Comment by SunboX** [comment]
I can't ignore the `error`. Firefox OS won't load the `sql.js` file if it contains an `eval()` call. :cry:

**Comment by SunboX** [comment]
Thx, I will try to build it. Any hint how to do this? Is it a "one liner" or do I need something more?

**Comment by lovasoa** [comment]
You need to install emscripten. Then, just clone this repository and run make.

**Comment by SunboX** [comment]
I'm getting this message, what I'm doing wrong?

```bash
$ make
coffee --bare --compile --join js/api.js --compile coffee/api.coffee coffee/exports.coffee coffee/api-data.coffee
make: coffee: No such file or directory
make: *** [js/api.js] Error 1
```

running it on Mac OS X

**Comment by lovasoa** [comment]
Yes, you need to install coffeescript. Sorry for forgetting to mention it.

**Comment by SunboX** [comment]
Ok, got it! Great, thanks a lot! :+1:
