### ISSUE TITLE
sql.js totaly freezes browser UI.

### ISSUE THREAD

**Issue by yurevich1** [kripken/sql.js#119]
How to fix it?
setTimeout and xhr do not help.

**Comment by lovasoa** [comment]
Use the webworker version of sql.js.

**Comment by lovasoa** [comment]
You can read [The code](http://kripken.github.io/sql.js/GUI/gui.js) of [the demo](http://kripken.github.io/sql.js/GUI/).

**Comment by yurevich1** [comment]
@lovasoa , Thanks.
