### ISSUE TITLE
More recent version of Sqlite?

### ISSUE THREAD

**Issue by mikeptweet** [kripken/sql.js#122]
Would it be possible to get this re-generated with a more current version of sqlite?

This is awesome, by the way!

**Comment by mikeptweet** [comment]
Any update on this? I can't build the product myself so this would be appreciated. Thanks

**Comment by gswilcox01** [comment]
I'm interested to.  Any plans to update to a recent version?

**Comment by lovasoa** [comment]
Fixed in #138
