### ISSUE TITLE
Insert throughput

### ISSUE THREAD

**Issue by unicomp21** [kripken/sql.js#123]
Can anyone give me a rough idea what sort of insert throughput I should expect?  w/o any indexes, I'm only getting ~100/s.

**Comment by dinedal** [comment]
Here's some tips:

 - Prepare your INSERT statement, do not make a new one each time.
 - Open a transaction, perform all the inserts, then close the transaction.
 - Move your work into a web worker, then build the database, so you can show progress in the UI.
