### ISSUE TITLE
<pathTo>/mydatabase.sqlite

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [kripken/sql.js#125]
Hello SQL.js team,

It seems your solution always uses a path to get the database which is a problem because we don't know what the path is in all the different devices.
But why don't you just use the basic window.openDatabase approach?

```
    if (!window.openDatabase) {
        alert('not supported');
    } else {
        var shortName = 'mydatabase';
        var version = ''; // '1.0'; // '';
        var displayName = 'My Important Database';
        var maxSize = 65536; // in bytes
        var mydb = openDatabase(shortName, version, displayName, maxSize);


```

Please advise,
Kind regards,
Mario

**Comment by lovasoa** [comment]
Hi,
  sql.js doesnt read files. The only way to open an existing database is to read it into memory (by your own means) and then giving the array of bytes to sql.jq.
