### ISSUE TITLE
.mode and .output not supported?

### ISSUE THREAD

**Issue by wxv** [kripken/sql.js#129]
The following works:

	var xhr = new XMLHttpRequest();
	xhr.open('GET', 'a.db', true);
	xhr.responseType = 'arraybuffer';

    xhr.onload = function(e) {
    	var uInt8Array = new Uint8Array(this.response);
    	var db = new SQL.Database(uInt8Array);
    	var contents = db.exec("SELECT * FROM listing");
    	console.log(contents[0]);  		
    };

But this doesn't:

    db.run(".mode csv");
    db.run(".output out.csv");

Error message:

    Uncaught Error: near ".": syntax error

**Comment by lovasoa** [comment]
This is a port of the sqlite library, not of the sqlite command line application.

**Comment by wxv** [comment]
Is there any other way to output as CSV? What I have given is the only method I've seen.

**Comment by AadhiKat** [comment]
Hi ! Did you find any of importing and exporting a csv file into this sqlite??

**Comment by lovasoa** [comment]
If you want to create a CSV, you can use a javascript CSV library.
https://www.npmjs.com/search?q=csv

**Comment by AadhiKat** [comment]
Thanks !  Will use that for loading the csv into sqlite
