### ISSUE TITLE
Consider documenting how to build from C source

### ISSUE THREAD

**Issue by oising** [kripken/sql.js#136]
So others can build on this great work and use newer versions of SQLite

**Comment by lovasoa** [comment]
You used to just have to run make. But I think it's broken on recent emscripten and sqlite. Contributions welcome.

**Comment by oising** [comment]
"make" is not a tool I'm accustomed to use on Windows.

I'm currently plowing through it in a haphazard manner, and I've gotten as far as to generate an a.out.js (aka sql.js) -- which is in turn is trying to require "fs", "path", and "crypto" modules when I load it with a browser loader. I'm at the point now where I'm using SystemJS to configure a map so it will pull in the browser-shimmed nodelibs to cover these requirements. I have no idea if this is going to work. 

My current problem is that I'm very confused as to how to enable the IndexedDb filesystem instead of the default MEMFS - I would have thought that logically this would have been a compiler switch, but I can't see anything? In fact now that I say that, shouldn't emscripten be providing the "fs" module, not node? Sigh... so confusing.

**Comment by lovasoa** [comment]
Make works on windows... If you don't want to use it, you should at least read the makefile to try and reproduce its steps. sqlite doesn't compile to JavaScript out of the box, and the makefile is charged to set the right options, and concatenate the right code so that it'll work.

**Comment by oising** [comment]
I totally missed the shell-pre and shell-pro scripts... thanks!
