### ISSUE TITLE
[Database API] multi-schema support

### ISSUE THREAD

**Issue by rognoni** [kripken/sql.js#145]
With the current implementation I have to use the `schema` hash map to manage different schemas:

```javascript
app.database = {
  schema: {},

  init: function() {

    var db = new SQL.Database();
    this.schema['info'] = db;
```
 
```javascript
var app = {
  main: function() {

    this.database.init();

    var db = this.database.schema['info'];
```

Is there a better way? for example using **AlaSQL** is more simple:

```javascript
var db = new alasql.Database("info");
```

```javascript
var db = alasql.databases["info"];
```

https://github.com/rognoni/adaptable/blob/master/Front-end/HTML5-Bootstrap4/database.js

**Comment by lovasoa** [comment]
The goal of this project is to be a mapping of SQLite interface to 
javascript. What I would advise is that you create and release your own 
library that does that.
