### ISSUE TITLE
Refused to execute script ("sql.js" on Chrome)

### ISSUE THREAD

**Issue by rognoni** [kripken/sql.js#148]
I see this error on Google Chrome:

```
Refused to execute script from
'https://raw.githubusercontent.com/kripken/sql.js/master/js/sql.js'
because its MIME type ('text/plain') is not executable, and strict MIME type checking
is enabled.
```
```
Uncaught ReferenceError: SQL is not defined
```
using this import:

```html
<script src="https://raw.githubusercontent.com/kripken/sql.js/master/js/sql.js"></script>
```

https://github.com/rognoni/adaptable/blob/master/Front-end/HTML5-Bootstrap4/index.html

A possible simple solution :-)
https://rawgit.com

**Comment by lovasoa** [comment]
This is normal, this is not an issue. There is no reason for them to give you bandwidth for free. You don't have right to include files from GitHub. Your are supposed to download them and serve them yourself. 

8 апреля 2016 г. 20:08:03 GMT+03:00, rognoni <notifications@github.com> пишет:
