### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [kripken/sql.js#156]
Hi @kripken ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
Now I just know `sql.js` should be added in cdnjs. And there exist `worker.js` and `worker.sql.js` in npm package. I'd like to confirm that if these two files need to be added in cdnjs. If there is any other file also need to be added please tell me, thank you.

https://github.com/cdnjs/cdnjs/issues/8449

**Comment by lovasoa** [comment]
You can refer to the Download section of the README, and choose which files you want to host from here.

**Comment by hfhchan** [comment]
@pvnr0082t 
For naming consistency with other projects,

https://raw.githubusercontent.com/kripken/sql.js/master/js/sql-debug.js
>> can be mapped to sql.js

https://raw.githubusercontent.com/kripken/sql.js/master/js/sql.js
>> can be mapped to sql.min.js

https://raw.githubusercontent.com/kripken/sql.js/master/js/worker.sql.js
>> can be mapped to sql.worker.min.js

https://raw.githubusercontent.com/kripken/sql.js/master/js/sql-memory-growth.js
>> can be mapped to sql.memory-growth.min.js

**Comment by pvnr0082t** [comment]
Ｔhanks @lovasoa @hfhchan , I'll try to send PR to add sql.js in cdnjs. :facepunch:

**Comment by pvnr0082t** [comment]
I'd like to confirm if the name of files including __raw__ in `js` folder also need to be added in cdnjs? It seems like not useful in cdnjs.
The list as following:
- sql-debug-raw.js.map
- sql-noopt-raw.js.map
- sql-raw.js.map

Thank you.

https://github.com/cdnjs/cdnjs/pull/8612

**Comment by lovasoa** [comment]
Indeed, you don't need to add these files. 

28 июля 2016 г. 10:56:20 GMT+02:00, Daniel Wang <notifications@github.com> пишет:

**Comment by pvnr0082t** [comment]
Thanks @lovasoa @hfhchan
