### ISSUE TITLE
when trying to use the SQL % Wildcard I get an error 

### ISSUE THREAD

**Issue by cardenasivan** [kripken/sql.js#162]
I'm using a select similar to the one below 

"SELECT ERPTYPE, SERVICEORDERNUMBER, ORDERTYPE, ORDERTYPEDESC, ORDERCLASSIFICATION, ORDERCLASSIFICATIONDESC, BUSINESSUNIT, EQUIPMENT, FUNCTIONALLOCN, ORDERSTATUS, ORDERSTATUSDESC, SYSTEMCONDITION, PRIORITY, PRIORITYDESC, ORDERDESCRIPTION, SYMPTOM, DISPATCHPRIORITY, SITEADDRESSKEY, OWNERKEY, PLANNEDSTARTDATE, PLANNEDSTARTTIME, PLANNEDFINISHEDDATE, PLANNEDFINISHEDTIME, REQUESTEDFINISHDATE, REQUESTEDFINISHTIME, ACTUALFINISHDATE, ACTUALFINISHTIME, PRIMARYTECH, PRIMARY_TECH_NAME, SECONDARYTECH, SECONDARY_TECH_NAME, MANAGER, MANAGER_NAME, SUPERVISOR, SUPERVISOR_NAME, ORIGINATOR, ORIGINATOR_NAME, CALLER, CALLERAREACODE, CALLERCONTACTNUMBER, SITENAME, STATUS, STATUS_DESC, NAME, ADDRESS1, ADDRESS2, ADDRESS3, ADDRESS4, CITY, STATE, POSTALCODE, SERVER_MESSAGE, EQUIPMENTDESCRIPTION, EQUIPMENTSERIALNUMBER, EQUIPMENTUNITNUMBER FROM VIEW_SVC_LIST WHERE ERPTYPE = JDE AND (STATUS = 0 OR STATUS LIKE 0 OR STATUS IS NULL) AND (SERVICEORDERNUMBER = % OR SERVICEORDERNUMBER LIKE %) AND (PRIORITY = % OR PRIORITY  LIKE %) AND (EQUIPMENT = % OR EQUIPMENT LIKE %) AND (PRIMARYTECH = % OR PRIMARYTECH LIKE %) AND (NAME = % OR NAME LIKE %) ORDER BY PLANNEDSTARTDATE"

And i get this error "Uncaught Error: near "%" Syntax error

**Comment by lovasoa** [comment]
This is because your SQL is invalid. You should use sql syntax as supported by SQLite. You can read their documentation on sqlite.org. 

17 августа 2016 г. 18:20:41 GMT+02:00, cardenasivan <notifications@github.com> пишет:

**Comment by sjurgis** [comment]
A valid example of valid wildcard using sample dataset at http://kripken.github.io/sql.js/GUI/ would be:
`SELECT name,hired_on FROM employees WHERE name LIKE '%on%'`
