### ISSUE TITLE
Question: update a value

### ISSUE THREAD

**Issue by hpfn** [kripken/sql.js#164]
Hi,

I do not know javascript. 

I want to use sql.js to update a value in sqlite3.db from
a html file. Using something like a ratio button. I want
to differ seen movies from unseen movies. That's
all I want. I will change the field in the sqlite3.db from 
0 to 1.

Is this possible ? I only see examples that start with
CREATE and using INSERT and SELECT.

regards,
Herbert

**Comment by lovasoa** [comment]
All requests that are possible in SQLite are possible in sql.js too. But if you don't know javascript at all, then it may be a little difficult for you to use this js library.
