### ISSUE TITLE
Can you do JOIN queries?

### ISSUE THREAD

**Issue by jasondavis** [kripken/sql.js#166]
Can you do JOIN queries across multiple tables with this library?

For example I have a bookmarks table, tags table, and a relationship table that connects tags records to the bookmark records and I need to join these in a query to get all bookmark records that belong to a particular tag record.

**Comment by lovasoa** [comment]
Of course you can. It works just like in the regular SQLite.

But did you mean between different *databases* ?

**Comment by maksimdegtyarev** [comment]
> But did you mean between different databases ?

Does sql.js can do JOIN queries between different databases?

**Comment by lovasoa** [comment]
Yes, just like regular sqlite: https://www.sqlite.org/lang_attach.html
But this mechanism is of fewer interest in sql.js, where everything 
happens in memory anyway.
And we don't expose access to the virtual filesystem where the database 
file is stored.

**Comment by dinedal** [comment]
Closing as resolved.
