### ISSUE TITLE
Fresh compile from latest emscripten is empty

### ISSUE THREAD

**Issue by jlongster** [kripken/sql.js#168]
I just installed emscripten and fastcomp from source, typed `make` and (after fixed several build problems...) the generated `sql.js` file is just:

``` js
// This prevents pollution of the global namespace
var SQL = (function () {
return this['SQL'];
})();
if (typeof module !== 'undefined') module.exports = SQL;
if (typeof define === 'function') define(SQL);
```

Is there some dead code removal going on? Any idea if this should just work with the latest emscripten?

**Comment by jlongster** [comment]
In this part of the Makefile:

```
optimized: EMFLAGS= --memory-init-file 0 --closure 1 -O3 -s INLINING_LIMIT=50 -s RESERVED_FUNCTION_POINTERS=64
```

Changing it from `-O3` to `-O2` fixes it.

**Comment by dinedal** [comment]
Closing, as I am not able to reproduce. Might have been a transient issue?

Also, we are updated to the latest emscripten and sqlite as of this writing.
