### ISSUE TITLE
Can this library handle the BLOB not fully loaded?

### ISSUE THREAD

**Issue by kochizufan** [kripken/sql.js#170]
Hi 

I have very huge sqlite file and handle it by this library before fully loaded.
Is it possible to access the blob partially loaded?

Only READ is need, CREATE/UPDATE/DELETE are no need.
Regards,

Kohei

**Comment by lovasoa** [comment]
This is not possible and will probably never be. This project is just a compilation of sqlite, that relies on synchronous reads to access the database file. So it cannot support a file that is not immediately fully accessible.

The simple thing for you to do is to split your database into multiple smaller databases. You could then copy data from the small databases to a main in-memory database on the fly, as they load.
