### ISSUE TITLE
Upgrade to latest sqlite build

### ISSUE THREAD

**Issue by mikeptweet** [kripken/sql.js#171]
Would it be possible to get this updated to the latest sqlite version?

I keep trying to build this myself and although although it seems to build correctly, whenever I try and use the resulting sql javascript files, I get a 'SQL is undefined' when I try and do var db = new SQL.Database();

I am attaching the resulting sql.js here to see if anything stands out
[sql.zip](https://github.com/kripken/sql.js/files/575704/sql.zip)

**Comment by dinedal** [comment]
Fixed https://github.com/kripken/sql.js/pull/176

**Comment by mikeptweet** [comment]
Awesome ... thanks
