### ISSUE TITLE
sql.js's process.on('uncaughtException') causing problems

### ISSUE THREAD

**Issue by MrBlenny** [kripken/sql.js#173]
This library binds to uncaughtException as follows:

``` javascript
process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
```

This causes incompatibilities with global uncaughtException handlers as seen in [this issue - related to electron](https://github.com/electron/electron/issues/7876).
Can sql.js's uncaughtException handler be changed? What are the implications of removing it?

**Comment by dinedal** [comment]
I'm not terribly familiar with how electron works, so forgive my ignorance if I misspeak.

Could you preserve your original `uncaughtException` function prior to requiring in sql.js, and reapply it after?

The `uncaughtException` code is not actually sql.js, but an artifact of emscripten which we use to compile sqlite to javascript.

**Comment by MrBlenny** [comment]
That didn't seem to work for me. 

I have removed sql.js's uncaughtException handler - that seemed to do the trick for me and hasn't caused any issues thus far.
