### ISSUE TITLE
Web Worker compiling bug

### ISSUE THREAD

**Issue by kevincolten** [kripken/sql.js#174]
Using the [web worker strategy](https://github.com/kripken/sql.js#use-as-web-worker) throws this error.

![screen shot 2016-11-10 at 8 50 18 am](https://cloud.githubusercontent.com/assets/4411115/20181258/0cce82a4-a723-11e6-9cb7-e627fc339ee4.png)

Probably a semicolon missing, ([related SO](http://stackoverflow.com/questions/30689310/anonymous-function-causing-problems)).

**Comment by Taytay** [comment]
I believe this is fixed in #255, as I have been able to use it as a web worker without issue.

**Comment by kevincolten** [comment]
Haven't tested it but closing since this is old
