### ISSUE TITLE
I'd like to help contribute and maintain this project

### ISSUE THREAD

**Issue by dinedal** [kripken/sql.js#175]
I've had a few PRs merged that have helped this project, and would like more autonomy in doing the work here.

Specifically I'd appreciate being able to merge and review PRs against the codebase.

If you, the maintainers, don't feel I am up to the task at present, I understand. Please let me know what I can do to reach a level where my contributions are to your satisfaction.

**Comment by dinedal** [comment]
@kripken @lovasoa if you get a chance to respond, I'd appreciate it. I know you are both busy.

**Comment by lovasoa** [comment]
I'm sorry, but only @kripken can do that. I'm in favour of it!

**Comment by dinedal** [comment]
Totally understand @lovasoa and thanks for the support. Hopefully he will weigh in soon.

**Comment by dinedal** [comment]
Thanks @kripken ! I appreciate it, and all the work you've done so far. I hope I can help keep things moving here :)

**Comment by Taytay** [comment]
This is great news. Thanks @dinedal for stepping up!
