### ISSUE TITLE
Release latest version on NPM?

### ISSUE THREAD

**Issue by Taytay** [kripken/sql.js#179]
It looks like SQL.js was improved to use the latest version of SQLite3 and emscripten recently, but the NPM package hasn't been updated since March 24th. Any chance you could publish the latest version so we could give it a go? Thanks!

**Comment by lovasoa** [comment]
Of course :+1: Let's do that

**Comment by lovasoa** [comment]
:roll_eyes: Tests don't pass! I just `git pull` and `npm test`, and **there is a worker test that fails** !

**Comment by dinedal** [comment]
@lovasoa what node version? I'm not able to repro?

**Comment by lovasoa** [comment]
Yes, and I see that travis-CI successfully passes all tests too. [![Build Status](https://travis-ci.org/kripken/sql.js.svg?branch=master)](https://travis-ci.org/kripken/sql.js)

Node v6.2.2
The test that fails is the one with BLOBs inside web workers.

```
    ✗ Reading BLOB
      Expected: 
    [
      0,
      66
    ]
      Actual: 
    [
    
    ]
```

**Comment by lovasoa** [comment]
Yes, the problem is related to the node version: https://travis-ci.org/kripken/sql.js/builds/177810598

**Comment by dinedal** [comment]
@lovasoa https://github.com/kripken/sql.js/pull/121 is still the issue.

I've looked into this for a few days. I've come to the conclusion we would need to do a non trivial amount of work to worker.js to fix it the way proposed there.

**Comment by lovasoa** [comment]
Maybe we should use an other implementation of web workers ? https://www.npmjs.com/package/webworker-threads for instance ?
I'll try that.

**Comment by lovasoa** [comment]
Unfortunately, it doesn't work either.

**Comment by dinedal** [comment]
Yeah, the implementation of "the structured clone algorithm in Javascript as a separate project" is where we would need to start...

That is, as long as we aren't open to the idea of forking / creating our own modified workerjs that patches this issue in a custom way.

**Comment by lovasoa** [comment]
Isn't there any fully working javascript serializer out there ?

**Comment by dinedal** [comment]
The ones that I found had difficulty dealing with Blob / UInt8Array types, but perhaps I didn't try enough of them.

**Comment by lovasoa** [comment]
I think I found one: https://www.npmjs.com/package/bson
See: https://runkit.com/580f350772ebca0014ce054e/58338521cf2933001455b100

Forking workerjs to use bson shouldn't be too hard...

**Comment by dinedal** [comment]
I'll take it on next chance I get, unless you want to go for it

**Comment by lovasoa** [comment]
Since the failing test is in fact a known issue that only concerns WebWorker on node, I am still going to publish to NPM :smile:

**Comment by Taytay** [comment]
Thank you!

**Comment by linonetwo** [comment]
```
npm i sql-wasm.js     
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sql-wasm.js - Not found
```

**Comment by lovasoa** [comment]
The name of this project and the name of our npm package is `sql.js` not `sql-wasm.js`. 

https://www.npmjs.com/package/sql.js

**Comment by linonetwo** [comment]
Ok, maybe some of the example are out dated.
