### ISSUE TITLE
webworker test fails with recent versions of node

### ISSUE THREAD

**Issue by lovasoa** [kripken/sql.js#180]
This is the prolongation of the discussion started in #179 

[Webworker-threads](https://github.com/audreyt/node-webworker-threads) already uses BSON for serialization/deserialization. They currently [have a bug with typed array](https://github.com/audreyt/node-webworker-threads/issues/131), but fixing it seems to just be a matter of updating the version of BSON they use. Their maintainer happens to also be a minister of Taiwan, and [says she doesn't have a lot free time to handle this](https://github.com/audreyt/node-webworker-threads/issues/131#issuecomment-262105740). @dinedal, would you be interested in making her a pull request, and then replace our devDependency from the unmaintained *workerjs* to *worker-threads* ?

**Comment by lovasoa** [comment]
Oh, it even looks like node's native parent-child communication supports sending Uint8Arrays. Fixing *workerjs* would be very easy.

**Comment by dinedal** [comment]
> Oh, it even looks like node's native parent-child communication supports sending Uint8Arrays. Fixing workerjs would be very easy.

Doesn't seem to be the case, test still fails even once I blast away JSON from workerjs
