### ISSUE TITLE
Cannot INSERT into database (node)

### ISSUE THREAD

**Issue by mikekok** [kripken/sql.js#191]
I'm using sql.js in an Electron app, and although I can successfully retrieve data using db.exec and SELECT, I cannot INSERT anything into my database using db.run.

**Comment by lovasoa** [comment]
What exactly are you expecting ? INSERT works, it’s just that the DB is in memory, you have to handle file saving yourself if you want to persist your data.

**Comment by lovasoa** [comment]
Plus, if you are doing a desktop app, then you’d better not use this library, but a native one.

**Comment by lovasoa** [comment]
For instance https://www.npmjs.com/package/sqlite

**Comment by mikekok** [comment]
Thanks for letting me know.

**Comment by Zayelion** [comment]
I'm having the issue this @mikekok is describing. 

I created a blank database (in memory), created tables in it (in memory), then tried to run an series of `INSERT` commands. When the code get to the that part it crashes, as in throws the following exception.

```
Error: "Database closed"
sql.js:490
    at a.run (c:\Users\Jamezs\Documents\GitHub\YGO_DB\node_modules\sql.js\js\sql.js:490:256)
    at generateCDB (c:\Users\Jamezs\Documents\GitHub\YGO_DB\generator.js:124:13)
    at (anonymous) (c:\Users\Jamezs\Documents\GitHub\YGO_DB\app.js:137:22)
    at exithandler (child_process.js:267:6)
    at emitTwo (events.js:126:12)
    at emit (events.js:214:6)
    at maybeClose (internal/child_process.js:925:15)
    at stream.socket.on (internal/child_process.js:346:10)
    at emitOne (events.js:116:12)
    at emit (events.js:211:6)
    at _handle.close (net.js:554:11)

```

**Comment by dinedal** [comment]
I use sql.js in memory without issue for my app, inserting, deleting, selecting, etc.

I don't know enough about your code to say what's wrong. I see `cdb` is your sql.js db, but what is `db` ?

**Comment by Zayelion** [comment]
I figured it out, my `.join(',')` needed to be `.join(' , ')`. But the error message was very unhelpful for tracking down the cause of the error. @dinedal thank you for responding.

I suggest that if the SQL is malformed a different error be thrown.

**Comment by dinedal** [comment]
That's a good point, it's likely in the handleError function: https://github.com/kripken/sql.js/blob/master/coffee/api.coffee#L423-L428
