### ISSUE TITLE
External database updates not returned by SELECT query

### ISSUE THREAD

**Issue by maxwondercorn** [kripken/sql.js#193]
I'm using sql.js in an electron app and have issues with records added externally to the database.  If I add a record with an external program (SQLiteStudio in this case)  

    results = db.exec('SELECT * FROM table') 

won't return the new record(s).  I open the database before the the query and close afterwards.

The only way to see the new records is by refreshing the app/browser window.  It seems that the database is buffered.  I would not expect that if I'm doing a database close after accessing it.

**Comment by zirill** [comment]
Can Node.JS solve your problem

**Comment by maxwondercorn** [comment]
Since this is an electron app - node.js is already being used.  I have considered this might be a problem with multiple connections/record locking but refreshing the electron window shouldn't fix it in that case. I wanted to test that a bit further but haven't had a chance to get back to that project.  Hopefully tommorrow

**Comment by Hotinly** [comment]
I run` db.run("insert into hello (a, b) values(3, 'qqq')");` but I can't find this record in the file: `data.db`.
Is need to export the real file each time ?
