### ISSUE TITLE
Insert with create_function

### ISSUE THREAD

**Issue by kevin00000000** [kripken/sql.js#200]
I want to insert a message into the table and I must handle some data before inserting
```
let GetValue = function (key, msg){
        if(msg.hasOwnProperty(key)){
            return msg[key]
        }else{
            return ''
        }
    }
db.create_function("GetValue", GetValue)
for(let index in msgs){
        let msg = msgs[index]
        sql = "INSERT INTO im (msgid, caseid, casetype, senderid, sendername, sendtime, msgtype, msgcontent, msgsize, needack, sendorrecv, isread, issend)\
            VALUES (GetValue('msgid', msg), GetValue('caseid', msg), GetValue('casetype', msg), GetValue('senderid', msg), GetValue('sendername', msg), GetValue('sendtime', msg), GetValue('msgtype', msg), GetValue('msgcontent', msg), \
            GetValue('msgsize', msg), GetValue('needack', msg), GetValue('sendorrecv', msg), GetValue('isread',msg), GetValue('issend', msg));"
        db.run(sql)
    }
```
But I got a exception when execute run function: 

> no such column:msg

Then,why? and what should I do to transfer `msg` parameter into the function `GetValue`

**Comment by lovasoa** [comment]
You don't need to register an sql function here. Just get the values from JavaScript inside the loop and use a prepared statement. 
-- 
Простите за краткость, создано в K-9 Mail.

**Comment by kevin00000000** [comment]
> You don't need to register an sql function here. Just get the values from JavaScript inside the loop and use a prepared statement.

Thanks for your reply. Yes, of course. I know it work. But I want to know why a exception happened and what's kind of function I can use as a sql function or what's kind of parameter I must pass to the sql function.

Thanks again!

**Comment by lovasoa** [comment]
It does’nt work because you are trying to use the local javascript variable `msg` inside your SQL query. Of course, sqlite cannot access your local js variables. How would it do ?

For documentation about sql functions, read about them on SQLite's documentation. I think you are not clear about how SQL works. When you use an unquoted name in a query, it references a column of that name in the database. The database has no way to know what variables you are using in the programming language you are calling it from.

**Comment by kevin00000000** [comment]
Thank you! I see. Indeed a stupid question. :)
Because I don't know creating sql function is feasible in Sqlite,I thought  the function created by `create_function` was called in js enviroment and there was a reflection mechanism in js like Java.   
Anyway thanks!!
