### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fedarko** [kripken/sql.js#203]
Hi -- I'm getting ready to release some open-source software which uses sql.js. The README of sql.js says that sql.js is MIT licensed, but I can't find a copy of sql.js' particular version of the license anywhere (i.e. with the correct copyright info included). Is it available?

**Comment by Croydon** [comment]
@lovasoa Could you please do this? Or @kripken maybe

**Comment by kripken** [comment]
I added a license file now.

**Comment by fedarko** [comment]
Thank you!
