### ISSUE TITLE
Query not returning any results

### ISSUE THREAD

**Issue by warpdriv** [kripken/sql.js#207]
I could not find an answer anywhere else so I though I'd try here. My query is not returning any results. When I query my sqlite file with node.js it returns all the data.

Below is my code. When I step through it with the debugger the object contents is empty.

Any help is appreciated.

`﻿<html lang='en'>
<head>
    <script src="/static/js/lib/jquery.min.js"></script>
    <script src="/static/js/lib/sql.js"></script>
</head>
<body>

    <div id='data'></div>

    <script>
	try
	{
		console.log("we are here");
		var file = "/static/data/results.db3";

		var xhr = new XMLHttpRequest();
		xhr.open('GET', file, true);
		xhr.responseType = 'arraybuffer';

		xhr.onload = function() {
		try{
			var data = new Uint8Array(this.response);
			var db = new SQL.Database(data);
			var contents = db.exec('SELECT value FROM results');

			contents.forEach(function(row) {
			    console.log(row.value);
			});
		}
		catch(err){
			console.log(err.message);
		}
		};
		
		xhr.send();
	}
	catch(err)
	{
		document.getElementById("data").innerHTML = err.message;
	}
    </script>
</body>
</html>`

**Comment by JoshuaLicense** [comment]
The output object structure will be:

`[{ columns : array(x), values : array(x) }, {...} ]`

So to log all the records returned it would be:

`contents[0].values.forEach((row) => { 
  console.log(row);
});`

If you want to the rows like an object try using this:

```
var stmt= db.prepare('SELECT value FROM results');

while(stmt.step()) {
var row = stmt.getAsObject();
console.log(row.value);
}
```
