### ISSUE TITLE
Is there a WebAssembly version of sql.js?

### ISSUE THREAD

**Issue by Taytay** [kripken/sql.js#219]
I have a limited understanding of WebAssembly, but my understanding is that we'd see better performance if this was actually compiled directly to WebAssembly, rather than "only" asm.js. If that's correct, has anyone made the edits to the toolchain to support it, or are there pre-compiled files available on any of this projects' branches? If I wanted to look into doing so, can anyone point me in the right direction to begin digging in?

**Comment by kripken** [comment]
To try it, you need to pass `-s WASM=1` to emcc. Issues that you might need to deal with are that there will be another output file, a `.wasm` (which you can avoid with `-s SINGLE_FILE=1` but it's less efficient), and that startup may be async (as wasm compilation is async).

**Comment by Taytay** [comment]
Thank you sir! Much appreciated!

**Comment by mikeptweet** [comment]
Did you get a WebAssembly version to work?

**Comment by sebastianmacias** [comment]
I'm also looking forward to this.

**Comment by YagoLopez** [comment]
Me too

**Comment by Taytay** [comment]
I haven’t even attempted this since I asked 
:(

I did stumble across this project though in a recent search: https://github.com/mandel59/sqlite-wasm

It’s not active but maybe that’s because it just works @mandel59?

**Comment by Taytay** [comment]
I've started work on this, and have a work-in-progress branch here: https://github.com/Taytay/sql.js/tree/wasm

It depends on other non-wasm fixes I've made here: https://github.com/Taytay/sql.js/tree/fix/async_loading

More details, and a PR to come.

**Comment by Taytay** [comment]
PR here: https://github.com/kripken/sql.js/pull/255

**Comment by Taytay** [comment]
And if folks are reading this, they might be interested in another branch I've started where I'm trying to optimize things. So far, I've gotten the .wasm file down to 571KB: https://github.com/Taytay/sql.js/pull/1
