### ISSUE TITLE
asm.js errors out on Edge 16.16299

### ISSUE THREAD

**Issue by albertodotcom** [kripken/sql.js#220]
Hi, when we load `sql.js` on the last version of `Edge` (`16.16299`), we get this exception: `Compiling asm.js failed.`.
We are using the memory-growth `0.4.0` version of the library.
Any idea on how to fix it?
Thanks for your work 👏

**Comment by kripken** [comment]
Memory growth will no longer work as asm.js in firefox too, browsers decided to stop supporting it. The focus is on memory growth in WebAssembly.

The growth version should still work, though, just not with asm.js optimizations, so maybe it's slower.

**Comment by albertodotcom** [comment]
Thanks for the heads up.
We tried downloading the last compiled version from the repo, which differs from the version `0.4.0` published on npm, and it does work correctly so maybe it's just the matter of publishing a new version.
Thanks.
