### ISSUE TITLE
"CREATE TABLE" & "DROP TABLE" querys are not executing

### ISSUE THREAD

**Issue by ThatsEli** [kripken/sql.js#223]
Hey, If I try to execute a query with "CREATE TABLE" eg.
`CREATE TABLE "testName" (  "testField" TEXT);`
it doesn't work. There isn't any error printed on the console and undefined is being returned. If I try to edit the database with another tool like DB Browser for SQLite the query works :/ This also applies to a "DROP TABLE" query like 
`DROP TABLE IF EXISTS "testTable"` .
"INSERT" and "SELECT" are working perfectly fine 🤔

**Comment by lovasoa** [comment]
Please read the documentation.

> sql.js is a port of SQLite to JavaScript, by compiling the SQLite C code with Emscripten. It uses a virtual database file stored in memory, and thus doesn't persist the changes made to the database. However, it allows you to import any existing sqlite file, and to export the created database as a javascript typed array.

**Comment by ThatsEli** [comment]
I read the docs. The changes don't apply to the DB (in memory) at all. Exporting (with the export() function) the DB and saving it to a local file for inspection with "DB Browser for SQLite" confirms that. (It works with other statements like "INSERT" or "SELECT") I should have added this to my issue, sorry.

**Comment by lovasoa** [comment]
Can you post a minimal code snippet that would demonstrate the problem?
 Excuse my scepticism, but we have a lot of tests, and "create table" not working would be a major bug...

**Comment by ThatsEli** [comment]
Okay, I just recloned my Repo(had to reinstall Linux) and it works :/ I used the prebuild npm package (as before) and it works... Sorry for bothering you!

**Comment by lovasoa** [comment]
Ok, no problem :)
