### ISSUE TITLE
writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!

### ISSUE THREAD

**Issue by kirkouimet** [kripken/sql.js#232]
I'm getting this warning when using the latest master version of sql.js:

    writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!

Any idea on how to resolve?

**Comment by moeiscool** [comment]
just hit this now myself

**Comment by jienco** [comment]
I am having this warning too, being thrown when using sql.js in unit tests with jest + typeorm.

**Comment by vietnux** [comment]
me too ???
helpme

**Comment by moeiscool** [comment]
i think sql.js just doesn't work anymore

**Comment by jcubic** [comment]
The warning is still there. It works but give this message, it seems that `exec` function call `writeStringToMemory` and since it's Emscripten then maybe this came from SQLite code.

**Comment by acrodrig** [comment]
Would love to have this resolved as well.

**Comment by jkoenig134** [comment]
Same here.

**Comment by Taytay** [comment]
Fixed in #255
