### ISSUE TITLE
Uncaught Error: no such function: json_extract

### ISSUE THREAD

**Issue by kimown** [kripken/sql.js#237]
I want use [json1](https://sqlite.org/json1.html) in sql.js, I test some sql snippet in [online demo](http://kripken.github.io/sql.js/GUI/)

```
create table user (name text,phone JSON );
insert into user (name, phone) values("oz",'{"cell":"+491765", "home":"+498973"}');
select user.phone from user where user.name=='oz';
select json_extract(user.phone, '$.cell') from user;
```
[reference](https://stackoverflow.com/questions/33432421/sqlite-json1-example-for-json-extract-set)

![image](https://user-images.githubusercontent.com/7932380/38793803-3dde4156-4185-11e8-8602-68fc33c5282a.png)

but throw error : Uncaught Error: no such function: json_extract, how can I enable JSON1 extension, should I change [Makefile](https://github.com/kripken/sql.js/blob/master/Makefile) like FTS5 extension.
https://github.com/kripken/sql.js/pull/199

https://github.com/kripken/sql.js/issues/68

**Comment by lovasoa** [comment]
Yes, you should update the Makefile
