### ISSUE TITLE
SQLite 3.26.0

### ISSUE THREAD

**Issue by brodybits** [kripken/sql.js#258]
SQLite 3.26.0 resolves the well-known vulnerability described in <https://blade.tencent.com/magellan/index_en.html>.

I am using SQL.js in a test library for a client, who is using SQLite in a Cordova mobile app. We would like to use the same version of SQLite in both the test library and the mobile app.

**Comment by Taytay** [comment]
I've updated to 3.28.0 in #255

**Comment by brodybits** [comment]
Thanks @Taytay, hope they will integrate it soon!
