### ISSUE TITLE
Sorry to ask but is this project dead?

### ISSUE THREAD

**Issue by gustavomick** [kripken/sql.js#261]

**Comment by lovasoa** [comment]
I currently do not have much time to work on it. But I accept pull requests

**Comment by gustavomick** [comment]
@lovasoa thanks, besides actual improvements and refinements, i wanna understand if make sense to follow this approach or we can assume that indexeddb finally killed sql on web. any thought is appreciated. thanks

**Comment by lovasoa** [comment]
[IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) is more widely used than sql.js, executes "queries" faster, and is persistent by default. I think it should be the go-to solution if your application does not need SQL. In some cases, you want to open existing sqlite files, or run existing SQL queries. In these cases, sql.js is fine.
