### ISSUE TITLE
sql-debug.js:403701 Uncaught Error: cannot modify Event because it is a view(…)

### ISSUE THREAD

**Issue by arehman849** [kripken/sql.js#263]
![event_view_error](https://user-images.githubusercontent.com/40396240/54578970-8827cb00-4a27-11e9-8f91-5eb79a423601.JPG)
```
                  var keys = Object.keys(event),
			values = Object.values(event),
			sql = "",
			keyString = "",
			table = stbData.epg.columnsToAdjustTime ? "Event2" : "Event";
			keys.forEach(function(key, index) {
				keyString += key + "= ?";
				if(index < values.length-1) {
					keyString += ", ";
				}
				
			})
			if (update === 1) {
				sql = "INSERT INTO " + table + " (" + keys.join(", ") + ") VALUES (" +Array(keys.length).join("?, ") + "?);"
			} else {
				sql = "UPDATE " + table + " SET " + keyString + " WHERE eventId = '" + event.eventId + "'; " || + "' UniqueEventId = '" + event.UniqueEventId + "'; ";
			}

			var stmt = stbData.epg.db.run(sql, values);
```

i am unable to insert any rows to table Event2 it always throw me an error saying "cannot modify event since it is a view" 

please note: Event is a view and Event2 is a table and i am trying to insert it into Event2

final query would be formed as given below: 
`"INSERT INTO Event2 (eventId, UniqueEventId, serviceId, startTime, endTime, ageRating, title, shortDesc, longDesc, seriesId, episodeId, ActorCast, Director, OriginalName, EpisodeName, ProdYear, Country, EventGenres, sourceId, CatchupStartover, DisplaySeasonEpisode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);"`

**Comment by lovasoa** [comment]
It does not seem to be an sql.js related problem...

**Comment by arehman849** [comment]
why is it complaining of a view when i a trying to insert data to a table..

how i achieved creating a view
step 1 : created Event table with required columns.
step2 : based on a flag (columnsToAdjustTime) if true i rename the table Event to Event2.
step3 : after renaming i create a View out of Event2 table and name it as Event

with this i have both table and view with names Event2 and Event respectively. 

for the above said setup when i try to insert any new row to table (i.e. Event2) it always throw me an error where as i am able to insert data for the table which doesn't have any view associated to it

**Comment by lovasoa** [comment]
You should make sure you do not have a bug in your code. Maybe it is telling you that `Event` is a table because it is indeed a table. You can reopen this issue if you make a [Short, Self Contained, Correct example](http://sscce.org/) of the problem.
