### ISSUE TITLE
GUI Example stopped working with latest update

### ISSUE THREAD

**Issue by mikeptweet** [kripken/sql.js#265]
With the latest  update, the online GUI example stopped working ... it looks like it cannot load worker.sql-wasm.js. I tried it in both the latest Chrome and Firefox.

![image](https://user-images.githubusercontent.com/1769876/56950889-0f7d5980-6b11-11e9-8d2b-cbbc9a428e56.png)

**Comment by lovasoa** [comment]
I've seen that ! I have to recompile the demo. I'll do that soon.
