### ISSUE TITLE
Use tags

### ISSUE THREAD

**Issue by frontenddeveloping** [kripken/sql.js#266]
Subj

**Comment by lovasoa** [comment]
subj ? can you please explain your issue using a full sentence in English?

**Comment by frontenddeveloping** [comment]
This project doesn't use tags in github
So if you added sql.js to the project  via github link in the package.json you will receive every update in master branch. So, last WebAssembly update will broke a lot of projects.
I have to fork and revert this commits to keep it stable.

**Comment by lovasoa** [comment]
I added a `v1.0.0` tag. However, you should not depend on the git master branch of any project in your  package.json. Instead, use our [npm package](https://www.npmjs.com/package/sql.js).

And even if you absolutely need to depend on git, you should depend on a git repository you own. You can then merge updates from the remote repository.
