### ISSUE TITLE
resolveModule is never called

### ISSUE THREAD

**Issue by linonetwo** [kripken/sql.js#271]
https://github.com/kripken/sql.js/blob/bea97a08ce04a008482160b4f5d108f636602c27/dist/sql-wasm.js#L49

When I run it in nodejs, it it called and working properly, but in electron v5.0.1, it's never called, and Promise never resolved, it just waiting forever.

Maybe it should reject so I can know what happened?

**Comment by lovasoa** [comment]
Can you please release a minimal electron app exposing the bug?

**Comment by linonetwo** [comment]
Ouch, I'm using sqlite3 binary in `exec(`sqlite3 xx.sql "SOME_SQL"` instead...

I'm writing a plugin for an electron app, so minimal example is not easy to construct, closing this for now...
