### ISSUE TITLE
Lower memory usage

### ISSUE THREAD

**Issue by ryan-codingintrigue** [kripken/sql.js#272]
I know sql.js loads the database into memory, but there appears to be very high memory usage before a database is even loaded.

Consider the following code in NodeJS v10:
```
const init = require('sql.js');

(async () => {
    const sql = await init();
    await new Promise(resolve => setTimeout(resolve, 5000));
})();
```
This is a snapshot of the process:
![image](https://user-images.githubusercontent.com/9048902/57936302-86f60b80-78bb-11e9-82a6-a366efaff903.png)

That's 180Mb before I've even loaded the database. Struggling to see where this memory is used given that the .wasm is 2Mb and the .js is 1Mb...

**Comment by lovasoa** [comment]
I cannot reproduce that locally with node 12.1

I see a 6Mb memory usage before initializing sql.js, and 42Mb after. It's large, but incomparable to the 170Mb you see.

I am going to leave this issue opened as a reference in case you or someone else wants to work on optimizing memory usage.

**Comment by ryan-codingintrigue** [comment]
Thanks for looking into this! Premature issue logging on my part! I will upgrade Node and try a different platform and see if I can get a consistent result.

**Comment by ryan-codingintrigue** [comment]
@lovasoa Can confirm that I am seeing the following Results:

Node `v10.15.3`
- **Linux**: ~200Mb (sometimes higher, sometimes lower)
- **OSX**: ~50Mb

Node `v12.2.0`
- **Linux**: ~50Mb
- **OSX**: ~50Mb

This does not appear to be an issue with SQL.js, it's either Emscripten or upstream node as I can reproduce this with a completely separate .wasm-based project

**Comment by lovasoa** [comment]
OK, thank you for your investigation
