### ISSUE TITLE
Cannot control CORS settings on request for wasm file

### ISSUE THREAD

**Issue by mshwery** [kripken/sql.js#280]
When storing assets like this in S3 or some object storage it seems we cannot control the fetch request's CORS settings when `sql-wasm.js` fetches the `.wasm` file from a different origin (via `locateFile`).

I don't necessarily want to enable CORS with `Access-Control-Allow-Origin`, but am curious if it's possible to set the request's mode to `no-cors` to fetch the resource with CORS disabled?

**Comment by mshwery** [comment]
Turns out I actually already have setup CORS and all other assets are requested just fine without any CORS error.

I'm guessing this is happening because the request gets made within `sql-wasm.js` with `same-origin` mode?

**Comment by mshwery** [comment]
Ah turns out we were missing one of the origins in our CORS settings. I'll go ahead and close this out, but I am curious if one could be able to change the fetch options.

**Comment by lovasoa** [comment]
This is an interesting question. The configuration exposed by sql.js comes from emscripten, you should ask the question there.
