### ISSUE TITLE
database size

### ISSUE THREAD

**Issue by kzimny** [kripken/sql.js#281]
I need to save up to 10k images in sqlite database as blobs, this is not a joke. The database becomes up to 2 Gb size, can I use sql.js even if sql.js works in memory? Does sql.js load all data into memory at startup? Please don't advice me to save the images on the disc instead into the db, this is a serious requirement not my wish. Thank you for any hints.

**Comment by lovasoa** [comment]
Why don't you just test it for yourself? It should work, it will just be super slow.
