### ISSUE TITLE
Feature request: Export to SQL instructions

### ISSUE THREAD

**Issue by gandreadis** [kripken/sql.js#289]
It would be great if you could export the database's contents+schema to SQL instructions! This would be equivalent to sqlite's `.dump` command. I'd personally use it over the current export functinoality, since it would be human-readable and also more portable. Let me know if this is something you would consider implementing!

**Comment by lovasoa** [comment]
Hello, and thank you for your interest in this project!
This is an interesting feature to implement. However, I think it would be better implemented as an external library rather than as part of sql.js itself.
If you create such a library, feel free to post a link to it here.

**Comment by schickling** [comment]
Based on my current understanding it should be quite easy  to expose the `.dump` functionality of Sqlite. Is there a particular reason why you don't want to expose it @lovasoa?

**Comment by kaizhu256** [comment]
the `.dump` command is not actually a sqlite-api that can be exposed/called.  its a buncha scripts glued/hacked together in sqlite's [shell.c](https://github.com/sqlite/sqlite/blob/version-3.38.5/src/shell.c.in#L8425).

i agree its a useful feature, but some hand-coding is needed to decouple/translate the glue-code in shell.c to webassembly.

**Comment by Jarred-Sumner** [comment]
> i agree its a useful feature, but some hand-coding is needed to decouple/translate the glue-code in shell.c to webassembly.

Have you tried the [`sqlite3_expanded_sql`](https://www.sqlite.org/c3ref/expanded_sql.html) function? It returns the SQL string for a bound statement, including variables used

Incase it helps, here is some C++ used in `bun:sqlite` that uses it:
```c++
JSC_DEFINE_HOST_FUNCTION(jsSQLStatementToStringFunction, (JSC::JSGlobalObject * lexicalGlobalObject, JSC::CallFrame* callFrame))
{
    JSC::VM& vm = lexicalGlobalObject->vm();
    JSSQLStatement* castedThis = jsDynamicCast<JSSQLStatement*>(callFrame->thisValue());
    auto scope = DECLARE_THROW_SCOPE(vm);

    CHECK_THIS
    
   // ---- The relevant line ---- 
    char* string = sqlite3_expanded_sql(castedThis->stmt);

    if (!string) {
        RELEASE_AND_RETURN(scope, JSValue::encode(jsEmptyString(vm)));
    }
    size_t length = strlen(string);
    JSString* jsString = JSC::jsString(vm, WTF::String::fromUTF8(string, length));
    sqlite3_free(string);

    RELEASE_AND_RETURN(scope, JSValue::encode(jsString));
}
```
