### ISSUE TITLE
Will full outer joins ever be supported?

### ISSUE THREAD

**Issue by paul-kline** [kripken/sql.js#292]
Using the ['full featured' demo](http://kripken.github.io/sql.js/examples/GUI/) listed in the README, I see that performing a full outer join results in a console message stating full outer joins are not currently supported. Is the demo just old? Will Full joins ever be supported?

example:
```DROP TABLE IF EXISTS X;
CREATE TABLE X(a text, b int);

  INSERT INTO X VALUES ('a',1);
  INSERT INTO X VALUES ('b',2);
  INSERT INTO X VALUES ('c',3);
  INSERT INTO X VALUES ('d',4);
  INSERT INTO X VALUES ('e',5);

DROP TABLE IF EXISTS Y;
CREATE TABLE Y(c text, d int, e int);

  INSERT INTO Y VALUES ('t',1,5);
  INSERT INTO Y VALUES ('g',1,6);
  INSERT INTO Y VALUES ('f',2,7);
  INSERT INTO Y VALUES ('d',2,8);
  INSERT INTO Y VALUES ('h',3,9);
  INSERT INTO Y VALUES ('a',4,12);

select * from X full join Y ON X.b=Y.d;

**Comment by lovasoa** [comment]
sql.js is only a port of sqlite to JavaScript. The set of supported features strictly depends on sqlite. 

See https://www.sqlite.org/omitted.html

**Comment by lovasoa** [comment]
so the answer to the question is: not until sqlite supports it.
