### ISSUE TITLE
Double values losing precision without any arithmetic

### ISSUE THREAD

**Issue by AnyhowStep** [kripken/sql.js#295]
```sql
SELECT
  1e+300,
  -1e+300,
  1.23e+300,
  -1.23e+300,
  1.23e-300,
  -1.23e-300
```

Expected:

1e+300 | -1e+300 | 1.23e+300 | -1.23e+300 | 1.23e-300 | -1.23e-300
-- | -- | -- | -- | -- | --
1e+300 | -1e+300 | 1.23e+300 | -1.23e+300 | 1.23e-300 | -1.23e-300

Actual:

1e+300 | -1e+300 | 1.23e+300 | -1.23e+300 | 1.23e-300 | -1.23e-300
-- | -- | -- | -- | -- | --
1.0000000000000005e+300 | -1.0000000000000005e+300 | 1.2300000000000007e+300 | -1.2300000000000007e+300 | 1.2299999999999995e-300 | -1.2299999999999995e-300

-----

I'm pretty sure those double values can be represented losslessly with a `double` type.

-----

For reference,

https://www.db-fiddle.com/f/vvtNQMEZ4FGfpvmRp3Linv/0

Running the query in db-fiddle gives the following,

---

**Schema (SQLite v3.26)**

    SELECT
      1e+300,
      -1e+300,
      1.23e+300,
      -1.23e+300,
      1.23e-300,
      -1.23e-300;

| 1e+300 | -1e+300 | 1.23e+300 | -1.23e+300 | 1.23e-300 | -1.23e-300 |
| ------ | ------- | --------- | ---------- | --------- | ---------- |
| 1e+300 | -1e+300 | 1.23e+300 | -1.23e+300 | 1.23e-300 | -1.23e-300 |

---

**Comment by AnyhowStep** [comment]
Whoops, I wrote #325 and completely forgot I had this open issue

**Comment by lovasoa** [comment]
I am closing this as a duplicate. The original issue is still opened and you can reference it if you make a PR for this bug.
