### ISSUE TITLE
Can't run two db.exec queries on the same data file

### ISSUE THREAD

**Issue by MHeisoku** [kripken/sql.js#301]
Not sure if this is possible, but I would like to load a SQLITE database once and then execute two queries and return the results to a function. The first db.exec query works fine, but the second returns the following error in the console: 

Error: near "UAINNER": syntax error sql-wasm-debug.js:701:13

I have tried creating new db objects or new file reader objects - nothing seems to help. Code is as follows - can anyone please advise whether this is a bug or working as intended:

```js
dbFileElm.onchange = function () {
    var f = dbFileElm.files[0];
    var r = new FileReader();

    var firstSqlString = "SELECT * FROM TABLE1";
    var secondSqlString = "SELECT * FROM TABLE2";

    r.onload = function () {
    var Uints = new Uint8Array(r.result);
    initSqlJs(config).then(function (SQL) {
        db = new SQL.Database(Uints);

        var firstResults = db.exec(firstSqlString);
        var secondResults = db.exec(secondSqlString);
        renderCharts(firstResults, secondResults);
        db.close();
    });
    }
    r.readAsArrayBuffer(f);
}
```

**Comment by lovasoa** [comment]
Is the code snippet you give really the one you tried ?

```
Error: near "UAINNER": syntax error sql-wasm-debug.js:701:13
```

The sql snippet you give does not contain the string `UAINNER`...

Please try your SQL queries in sqlite against the same database first, and reopen this issue if the query works in sqlite but not in sql.js. In that case, please include the query itself.

**Comment by MHeisoku** [comment]
My mistake - I had broken the second query across multiple concatenated strings and forgot to put a space between the end of my table alias and the beginning of my inner join clause. Sorry about that - seems I need to get some more sleep!

**Comment by lovasoa** [comment]
No problem :smiley: 

Next time, please create a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) and make sure you can reproduce the bug before opening an issue.
