### ISSUE TITLE
Async functions are causing issues with last_insert_rowid()

### ISSUE THREAD

**Issue by LeeRob97** [kripken/sql.js#303]
I switched to sql.js after Apple dropped support for Web SQL. One big issue that I am having is that Web SQL returned the insertID within the same transaction, sql.js does not do this when I call the .getAsObject() method. Therefore, when I query for last_insert_rowid() another insert has ran by then causing ID issues.

**Comment by lovasoa** [comment]
I am not sure I understand your issue. Can you please provide a [short, example](http://sscce.org/) of what you think is wrong ?

sql.js is fully synchronous, no "other insert" can run between two consecutive database method calls.

**Comment by lovasoa** [comment]
Feel free to reopen the issue if you can provide more details.
