### ISSUE TITLE
如何用JavaScript读取已导出的本地.db文件，浏览器端运行 ，不使用任何服务器。

### ISSUE THREAD

**Issue by yellowYiFeng** [kripken/sql.js#304]
如题。本人要做一个功能，数据库的.db文件已导出到本地，需要能够使用JavaScript直接读取数据库，然后将数据显示在页面上。

**Comment by Lursun** [comment]
你就做個 <input type="file" .... /> 查js 怎麼讀文字檔，得到字串，餵給sql.js

**Comment by lovasoa** [comment]
I'm sorry, but I can't read Chinese. From what I understood this is more of a question than a bug report, and GitHub issues are not a good place for that.
