### ISSUE TITLE
How to use JavaScript to restart the local.db file that has been started and run on the browser side without using any server

### ISSUE THREAD

**Issue by yellowYiFeng** [kripken/sql.js#305]
As title. I want to do a function, the database. Db file has been imported to the local, need to be able to use JavaScript directly read the database, and then the data will be displayed on the page.

**Comment by lovasoa** [comment]
as I already answered in the other issue, this is a question. It would have it's place on a forum. 
Please stop opening issues unless you have a bug to report or a feature request to make.
