### ISSUE TITLE
Version of binaries out of date

### ISSUE THREAD

**Issue by brodybits** [kripken/sql.js#314]
Shows April 2019 (2x) & SQLite 3.28.0, while update was done with SQLite 3.30.1 in dda3553f9b71fd91fe45dd5488a081c5e24e8e65 (I cannot tell which Emscripten version).

I wonder if there may be some way to automate this?

**Comment by lovasoa** [comment]
It is already automated. It is just that there has been no release since the commit you mention. On the releases page, you can see the number of commits since a release:

https://github.com/kripken/sql.js/releases/tag/v1.0.1

When a new release will be made, all the latest commits will be included.

**Comment by brodybits** [comment]
Thanks. Any idea when we can get a release with the new commits?

**Comment by lovasoa** [comment]
Ok, I just released v1.1.0

**Comment by brodybits** [comment]
Wrong SQLite version and wrong release date still seem to show up in README.md: https://github.com/kripken/sql.js#version-of-binaries
