### ISSUE TITLE
requireJS demo uses HTTP instead of HTTPS (mixed content)

### ISSUE THREAD

**Issue by SebAlbert** [kripken/sql.js#315]
The demo at https://kripken.github.io/sql.js/examples/requireJS.html results in the following error message on the Chrome browser console:

``
Mixed Content: The page at 'https://kripken.github.io/sql.js/examples/requireJS.html' was loaded over HTTPS, but requested an insecure script 'http://requirejs.org/docs/release/2.3.6/minified/require.js'. This request has been blocked; the content must be served over HTTPS.
``

**Comment by lovasoa** [comment]
Thank you for reporting this ! It's fixed.
