### ISSUE TITLE
loadExtension()

### ISSUE THREAD

**Issue by baptistapedro** [kripken/sql.js#316]
Hello,
I amusing sql.js on browser on my emscripten project.
I am trying to load an .wasm extension but it doesnt seem to support loadExtension()

```
config = {
    locateFile: filename => `/dist/${filename}`
}

initSqlJs(config).then(function(SQL){
    var db = new SQL.Database();
    db.loadExtension('myout.wasm');
    db.run("SELECT TESTFUNC('CREATE TABLE foo (bar TEXT)')");
});
```

Can you tell me what's the right way to load it?

Thanks.

**Comment by lovasoa** [comment]
Hello,
  There is no way to load an extension, and this feature is not trivial to implement at all. If you are interested in implementing it, let me know and I'll reopen this issue.

**Comment by mandel59** [comment]
Emscripten supports dynamic linking. (https://github.com/emscripten-core/emscripten/wiki/Linking) SQLite's run-time extension is just loaded by dlopen, so it will work if
- the main module (sqlite) is compiled with `-s MAIN_MODULE=1` option, and
- extensions are compiled with `-s SIDE_MODULE=1`.

SQLite disables run-time extension by default, so calling `sqlite3_db_config` is also needed.

I confirmed that WASM version of SQLite can load run-time extensions with code of my repository https://github.com/mandel59/sqlite-wasm
