### ISSUE TITLE
Performance compare to sqlite3

### ISSUE THREAD

**Issue by aminpaks** [kripken/sql.js#317]
I've been using sqlite3 for a while and been wanting to move to a native solution til I found this project recently so my first thought was **sql.js** must be faster than **sqlite3**.

So I tried the simplest test case and the results are strange, am I doing something wrong or **sql.js** is way slower than **sqlite3**?

### Benchmark source:
```js
const sqlite3 = require('sqlite3');
const initSql = require('sql.js');

async function main() {
  let db;
  let stmt;

  db = new sqlite3.Database(':memory:');

  console.time('sqlite3');
  db.serialize(() => {
    db.run('CREATE TABLE lorem (info TEXT);');

    stmt = db.prepare('INSERT INTO lorem VALUES (?);');
    for (var i = 0; i < 1000; i++) {
      stmt.run('Ipsum ' + i);
    }
    stmt.finalize();
    stmt = undefined;
  });
  console.timeEnd('sqlite3');
  db.close();

  const SQL = await initSql();
  db = new SQL.Database();

  console.time('sql.js');
  db.run('CREATE TABLE lorem (info TEXT);');

  stmt = db.prepare('INSERT INTO lorem VALUES ($text);');
  for (var i = 0; i < 1000; i++) {
    stmt.run({ $text: 'Ipsum ' + i });
  }
  stmt.free();
  stmt = undefined;
  console.timeEnd('sql.js');
  db.close();
}

main();

```

### Benchmark project
1. Pull down this project `$ git clone git@github.com:aminpaks/sqlite3-v-sqljs.git`
2. Install deps `$ npm install`
3. Start the benchmark by `$ npm start`

### Results (Node v12.13.1):
sqlite3: **14.594ms**
sql.js: **458.393ms**

**Comment by lovasoa** [comment]
You are not doing anything wrong, and sql.js is slower than any native alternative.
`sqlite3` contains native code compiled for your platform, whereas sql.js contains a wasm binary, that has to be interpreted or compiled on the fly. 

If you can, use `sqlite3`. If not (if your code has to run in a web browser, for instance) then use sql.js.
