### ISSUE TITLE
Latest build instructions?

### ISSUE THREAD

**Issue by AnyhowStep** [kripken/sql.js#326]
I've tried building the SQLite source on my own but noticed I'm getting a different `dist` output from what's in this repository.

Am I using the wrong version of `emsdk`?

In `emsdk`,
```
emsdk install latest
emsdk activate latest
source ./emsdk_env.sh
```

In `sql.js`,
```
npm run rebuild
```

Then,
```
git status
```

And my output,
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dist/sql-asm-debug.js
	modified:   dist/sql-asm-memory-growth.js
	modified:   dist/sql-asm.js
	modified:   dist/sql-wasm-debug.js
	modified:   dist/sql-wasm-debug.wasm
	modified:   dist/sql-wasm.js
	modified:   dist/sql-wasm.wasm
	modified:   dist/worker.sql-asm-debug.js
	modified:   dist/worker.sql-asm.js
	modified:   dist/worker.sql-wasm-debug.js
	modified:   dist/worker.sql-wasm.js
```

-----

It seems like my `emsdk` versions are,
```
         1.39.5
         1.39.5-fastcomp
```

**Comment by lovasoa** [comment]
We hope to delete the `dist` folder when we can. We have discussed it before in https://github.com/kripken/sql.js/pull/298

You can see the full build configuration in https://github.com/kripken/sql.js/blob/master/.github/workflows/release.yml

And the result in https://github.com/kripken/sql.js/releases
