### ISSUE TITLE
can you add.....

### ISSUE THREAD

**Issue by julientype** [kripken/sql.js#327]
```js
contents = dba.exec("SELECT * FROM aaa");
add page caching 

content = dba.execDataSet ("SELECT * FROM aaa" , rowsperpage);
returns a data-set object
content.rows.length =  100,000
content.curserpose     = pos in rowsperpage 
content.runNextPage
content.pageCount
content.pageAt
content.colum(1)= "aaaa" on currentRecPos
content.colum(2)= "adxxx" on currentRecPos
  
var response =  content.submitUpdate  on currentRecPos
content.addrec  = creates a virtual rec in the context object with a submit.
context.delete = the curent pos rec
```

A dataset controller object 

its the same  sql just resent or insert update delete ......

**Comment by lovasoa** [comment]
Hello,
  I don't think this enters the scope of this project. This could be implemented as an external library, though !

**Comment by julientype** [comment]
your managing rec at a the c level and to transfer large arrays is costly.....

**Comment by lovasoa** [comment]
You won't have to transfer any large array: just use the a prepared statement and call [`next`](http://kripken.github.io/sql.js/documentation/#http://kripken.github.io/sql.js/documentation/class/Statement.html) to get lines of result one by one. Do not hesitate to ping me if you feel stuck while implementing this.
