### ISSUE TITLE
whats the difference in sql.js and  Command Line Shell For SQLite

### ISSUE THREAD

**Issue by julientype** [kripken/sql.js#331]
here is the c lib tools.....
https://sqlite.org/cli.html

your not really  transferring the database  file  into an array are  you......
Emscripten can be used to compile almost any portable C/C++ code to JavaScript. 

you could open any size database and run array records back and forth by JavaScript.....

like windows adb shelll commands  to android sqlite database but done in JavaScript by porting it...

the c lib tool would fallow its container rules to set up  its open SQL pointers ... DOM has limits to what it can transfer in an array..... now you have the CPU working for you not the browser memory .... its just a waiter serving array records .... record edit locks would be supported also this way.....  

just trying to understand more..... Help.....

**Comment by lovasoa** [comment]
Can you please take the time to make full sentences, if you are asking for help ? Your messages are hard to understand. I am closing this issue, but do not hesitate to comment on it further or update your original message to make it clearer what you are asking.

**Comment by lovasoa** [comment]
> What is the difference between sql.js and the *Command Line Shell For SQLite* ?

sql.js is a javascript library that lets you interact with an SQLite database stored in memory from javascript code.
The [sqlite cli]( https://sqlite.org/cli.html) is a program that lets you interact with an SQLite database stored on disk or in memory through a terminal emulator.
