### ISSUE TITLE
load extension

### ISSUE THREAD

**Issue by baptistapedro** [kripken/sql.js#342]
Hello,
This lib support `load_extension` method?

**Comment by brodybits** [comment]
I think not, but it should be possible to embed custom C functions as I said here:

- <https://github.com/kripken/sql.js/pull/320>
- <https://github.com/kripken/sql.js/issues/310#issuecomment-587243120>

**Comment by lovasoa** [comment]
>  This lib support load_extension method?

No, load_extension is not supported by default. The easiest is to just compile your own sql.js directly with the extension you are  interested in.

**Comment by baptistapedro** [comment]
What about what @brodybits said?
I already have my extension as wasm file, I'm not sure how to use the wasm file with SQL.js

I definitely don't.know how to compile the sql.js with the extension.
Can you gimme details
