### ISSUE TITLE
how to set Cache=Shared

### ISSUE THREAD

**Issue by daonsh** [kripken/sql.js#343]
I get this error on running a batch of 17,000+ SQL commands in the example, pasted into the textarea:
worker.sql-wasm.js:82 Uncaught (in promise) Error: bad parameter or other API misuse

I have read that it may be caused by not using Cache=Shared as in:
https://github.com/aspnet/Microsoft.Data.Sqlite/issues/508

Is there a way to set in SQLjs similar to this line (in C#):
var con = new SqliteConnection();
con.ConnectionString = **"Data Source=test.db;Cache=Shared";**
con.Open();

Note the Cache=Shared above

Thanks

**Comment by lovasoa** [comment]
can you provide a minimal reproduction of your error?

**Comment by daonsh** [comment]
I wasn't able to reproduce. Nevermind, sorry.
