### ISSUE TITLE
cdnjs download seems to be way out of date

### ISSUE THREAD

**Issue by brodybits** [kripken/sql.js#346]
(0.5.0) compared to sql.js version 1.1.0

**Comment by lovasoa** [comment]
I opened an issue on their side. https://github.com/cdnjs/cdnjs/issues/13685

**Comment by lovasoa** [comment]
The latest version of the library is now available at https://cdnjs.com/libraries/sql.js

**Comment by brodybits** [comment]
Awesome thanks!
