### ISSUE TITLE
Import exported sqlite3 functions into another WASM module

### ISSUE THREAD

**Issue by Kegsay** [kripken/sql.js#352]
I'm currently compiling some Go code to WASM via `GOOS=js GOARCH=wasm`. This Go code will try to open (I guess via dlopen?) sqlite3: sqlite3 C code is NOT embedded in the Go WASM.

`sql.js` has a `sql-wasm.wasm` file which exports a whole bunch of functions as shown by `WebAssembly.Module.exports(compiledModule)`. Is it possible for me to somehow import these functions e.g via the `importObject` in `WebAssembly.instantiate` and then use them transparently via the underlying Go code? It feels like this might work but I lack enough knowledge on wasm/emscripten to be able to answer this. I know Emscripten seems to support dynamic linking and side modules, so I feel this is possible, even if I need to recompile sqlite3 myself.

Any help would be appreciated, especially from @kripken if at all possible!

Sources:
 - https://webassembly.org/docs/dynamic-linking/
 - https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone#create-a-dynamic-library

**Comment by lovasoa** [comment]
Hello !
  Unfortunately, I don't think this is possible to do without changing your go code to use imported functions instead of using dlopen.
  More details here: https://stackoverflow.com/questions/59727133/can-multiple-wasm-modules-interact-with-each-other-and-share-memory-directly-via
  If you have questions about how wasm works and how to achieve what you want, you can ask them on stackoverflow.

Cheers,

**Comment by Kegsay** [comment]
Thanks for the feedback, I appreciate it. Sorry this was a little off-topic :)

**Comment by kripken** [comment]
@Kegsay

Emscripten has support for dlopen, using the [tool convention for that](https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md). If Go's wasm support is compatible with that, then you can compile SQLite with emscripten as a dynamic library and load it from Go (note that the sql.js wasm build is *not* a dynamic library - dynamic libraries must support things like relocation, which add overhead, and are not done in normal builds).

Another option is to avoid dynamic linking, as @lovasoa said. If Go supports wasm object files, you can link them with compiled SQLite, but I'm not sure if it does.

Another possibility here might be to use TinyGo. It's LLVM based, so it might support wasm object files - LLVM does, but I'm not sure if TinyGo needs to do something to enable that.

(In the long term wasm Interface Types might help here.)

**Comment by Kegsay** [comment]
Fantastic thanks. I'll let you know how I get on because as far as I can tell, no one has done this in the Go ecosystem yet.
