### ISSUE TITLE
Can not enlarge memory array buffer

### ISSUE THREAD

**Issue by NasirNS45** [kripken/sql.js#357]
Hi there

I'm getting tonnes of:

Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
how can i resolve this error? Is there any way to resolve this memory issue?

**Comment by lovasoa** [comment]
Hello, 
  What version of sql.js are you using ?
  WASM builds (used by default) are compiled with memory growth enabled. In default asm.js builds, memory growth is disabled by default, but we also distribute `sql-asm-memory-growth.js` which is asm.js with memory growth enabled.

**Comment by NasirNS45** [comment]
I am using 0.4.0 version of Sql.js

**Comment by lovasoa** [comment]
Wow ! 0.4.0 is 3 years old. Can you try with the latest version ?
In old versions, you can still manually include `./node_modules/sql.js/js/sql-memory-growth.js` to get the version with memory growth enabled.

I am closing this since it doesn't seem to be an issue with sql.js itself, but feel free to comment below if you still encounter issues.

**Comment by NasirNS45** [comment]
with latest version I'm having issue saying that
 "TypeError: SQL.Database is not a constructor".
how can i get rid of this?

**Comment by lovasoa** [comment]
Read the documentation for the latest version.

You need to asynchronously initialize sql.js. Add `sql-wasm.wasm` to your assets and then 

```js
    const initSqlJs = require('sql.js');
    const SQL = await initSqlJs({
      locateFile: filename => `/path/to/your/assets/${filename}`
    });
    const db = new SQL.Database();
      ...

**Comment by NasirNS45** [comment]
I don't know what to do and how to do it? all things were working perfectly but all of sudden error raised at every page in my electron app. can you look at my code? I can send you js file.

**Comment by NasirNS45** [comment]
I was using different function to create, save and get data from database. But I don't know how to use the latest version. I am so confused. Kindly help me out if you can.

**Comment by lovasoa** [comment]
I am not going to debug your code for you. If you have a [short self-contained example](http://sscce.org/), I can have a look at it. But you need to provide more information if you need help. Also, please read all of the README.

**Comment by NasirNS45** [comment]
`const path = require('path')
const fs = require('fs')
const SQL = require('sql.js')
SQL.dbOpen = function (databaseFileName) {
  try {
    return new SQL.Database(fs.readFileSync(databaseFileName))
  } catch (error) {
    console.log("Can't open database file.", error.message)
    return null
  }
}
const getData = function (pid, tableName) {
  let db = SQL.dbOpen(window.model.db)
  if (db !== null) {
    let query = 'SELECT * FROM `' + tableName + '` WHERE `id` IS ?'
    let statement = db.prepare(query, [pid])
    try {
      if (statement.step()) {
        let values = [statement.get()]
        let columns = statement.getColumnNames()
        return _rowsFromSqlDataObject({ values: values, columns: columns })
      }
    } catch (error) {
    } finally {
      SQL.dbClose(db, window.model.db)
    }
  }
}`
kindly have a look.

**Comment by NasirNS45** [comment]
can i use sqlite3 offline, I mean as local database?

**Comment by lovasoa** [comment]
Yes. But why not checking that out yourself ? I don't want to be rude, but please read all of the documentation you can find online, and try things for yourself. The developers of the opensource libraries you use are happy to receive well-formed bug reports, but they probably don't have the time to provide technical support for free to all of their users. Please respect their time, and report bugs only once you have read all the docs and done all of the necessary debugging on your side.

**Comment by NasirNS45** [comment]
OK. Thanks for your time and guide and sorry for consuming your precious time.
