### ISSUE TITLE
Last inserted row id?

### ISSUE THREAD

**Issue by AAverin** [kripken/sql.js#77]
I kinda expected an insert statement to return me the id of inserted row, but I got an empty array instead.
If that's the correct behavior, any way I can get the latest inserted row id without making another select query?

**Comment by lovasoa** [comment]
I'm closing this for now. If anyone has a good argument in favor of the addition of a `last_insert_rowid()` method to the API, don't hesitate to reopen it.

**Comment by JanisE** [comment]
> For your use case, I would advise you to create a statement with `SELECT last_insert_rowid()` at the beginning of your script, and executing it when you need it.

I'm trying it like this, but I get `undefined` as the rowid:

```html
<!DOCTYPE html>
<html>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/sql-wasm.js"></script>
  <script>
    initSqlJs({locateFile: () => 'https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/sql-wasm.wasm'}).then(function(SQL){
      const db = new SQL.Database();
      db.run(`CREATE TABLE texts (
          id INTEGER PRIMARY KEY,
          text VARCHAR NOT NULL
        );`
      );

      const get_last_id = db.prepare('SELECT last_insert_rowid() AS lastid');
      const insert_text = db.prepare('INSERT INTO texts (text) VALUES (:text);');

      for(let i = 0; i < 5; i++){
        insert_text.run({':text': 'text'});
        console.log(get_last_id.getAsObject());
      }
    });
  </script>
</body>
```
