### ISSUE TITLE
Insert into - data don´t saved

### ISSUE THREAD

**Issue by baltazaroliveira** [kripken/sql.js#80]
What i am doing wrong? (Using on Mobile App).

// == SQL == //

        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'db/Catalogos.db', true); //async
        xhr.responseType = 'arraybuffer';

        //

        xhr.onload = function (e) {

            var uInt8Array = new Uint8Array(this.response);
            var db = new SQL.Database(uInt8Array);
                                    
            sqlstr = "INSERT INTO hl_NumeracaoAnoUtlzs VALUES, ('1','2','3');";
            
            
            console.info("1");
            db.run(sqlstr);
            /*
            console.info("2");
            db.exec(sqlstr);
            */
            
            // fecha a ligação á BD
            db.close();
        };
        xhr.send();

**Comment by shotgun469** [comment]
I am having a similar problem where I am inserting data into the sqlite3 file and it is not saving.

Is there any specific example where I can see what I'm missing?

Thanks,

**Comment by lovasoa** [comment]
There is nothing you are doing wrong. The database is loaded in memory, so it's lost as soon as you reload the page (or as your app terminates if you are using node).

**Comment by shotgun469** [comment]
@lovasoa Can you show me how to save into the file once we are done editing the data?

thanks

**Comment by lovasoa** [comment]
It depends if you want to save it to the server or to the client computer.
Sql.js allows you to export the data to a byte array, you can do whatever you want with it. I am not going to write your code.

**Comment by shotgun469** [comment]
Thanks for the guide

**Comment by Juliakater** [comment]
Hello Lovasoa.
very nice to meet you.
I am going to data into existing sqlite database using sql.js.
but it is not working.
I mean data don't save in database.
I hope to you help me.

**Comment by lovasoa** [comment]
Please read [the README](https://github.com/kripken/sql.js#sqlite-compiled-to-javascript)

sql.js is working entirely in memory. It cannot persist the data to your file, as it doesn't even know that the data you give it is coming from a file.

The library that suits the most is most probably not sql.js, but something like [sqlite from npm](https://www.npmjs.com/package/sqlite)
