### ISSUE TITLE
Compiling emscripten error

### ISSUE THREAD

**Issue by MicheleFioretto** [kripken/sql.js#81]
Hi,
     I'm trying to compile the Makefile using emscripten but I received this error:
<<
G:\>emmake G:\Research\sql.js\Makefile
ERROR    root: Exception thrown when invoking Popen in make with args: "G:\Resea
rch\sql.js\Makefile"!
Traceback (most recent call last):
  File "G:\Research\emscripten\emscripten\1.25.0\\emmake", line 26, in <module>
    shared.Building.make(sys.argv[1:])
  File "G:\Research\emscripten\emscripten\1.25.0\tools\shared.py", line 1074, in
 make process = Popen(args, stdout=stdout, stderr=stderr, env=env)
  File "G:\Research\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__errread, errwrite)
  File "G:\Research\emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948
, in _execute_child startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
>>

I'm using win8.1 x64.
Any help?

thanks 
Michele

**Comment by lovasoa** [comment]
I think you should report this bug to [emscripten](https://github.com/kripken/sql.js). The error is thrown from emscripten.

**Comment by lovasoa** [comment]
So I would advise that you first upgrade your emscripten to the latest version: 1.29 (you are using 1.25), try again, and if the problem still occurs, report a bug to emscripten.

**Comment by MicheleFioretto** [comment]
I had the same error even with the newer version of emscripten (I opened ad issue as You advised me). In order to generate sql.js do I have emscripten installed and execute makefile with this statement: "\\:>emmake G:\Research\sql.js\Makefile" ? There are any other steps I missing?
Many thanks 
Michele

**Comment by lovasoa** [comment]
No, you are not missing anything :)

I've never tried compiling it from windows, but it should work.
