### ISSUE TITLE
Reading SQLite database from file in browser

### ISSUE THREAD

**Issue by agershun** [kripken/sql.js#82]
Dear Alon,

could you add to the documentation of SQL.js the following example, how to read SQLite database from browser, like the code below or something similar:

```html
    <script src="sql.js"></script>
    <script>
        function loadBinaryFile(path,success) {
            var xhr = new XMLHttpRequest();
            xhr.open("GET", path, true); 
            xhr.responseType = "arraybuffer";
            xhr.onload = function() {
                var data = new Uint8Array(xhr.response);
                var arr = new Array();
                for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
                success(arr.join(""));
            };
            xhr.send();
        };

        loadBinaryFile('Chinook_Sqlite.sqlite', function(data){
            var sqldb = new SQL.Database(data);
            // Database is ready
            var res = db.exec("SELECT * FROM Genre");
        });
    </script>
```
This is a [working example](http://alasql.org/demo/016sqlite/).

I am asking you, because some people do not know, how they can to do it from browser (see [this question](http://stackoverflow.com/questions/28066570/read-sqlite-database-from-the-disk-using-sql-js/28069518#28069518) at Stackoverflow.com)
Thank you for the database!

**Comment by lovasoa** [comment]
Hello,
  Alon Zakai does not maintain `sql.js` anymore.
  The exemple you give doesn't work with a recent version of sql.js.

  There is an example of how to do this in the wiki: https://github.com/kripken/sql.js/wiki/Load-a-database-from-the-server.
  I am going to add this example to the README.
