### ISSUE TITLE
Loading a database using Web Workers via XMLHttpRequest

### ISSUE THREAD

**Issue by jasdeepkhalsa** [kripken/sql.js#85]
Ideally I wanted to use the Web Worker script `worker.sql.js` and have it fetch the SQLite database via a XMLHttpRequest GET on its side and then turn it into an ArrayBuffer, rather than me posting the entire ArrayBuffer with the `postMessage` to the Web Worker (which is currently the case AFAIK?) and which to me logically sounds like it would not be the most performant thing to do. Since I'm developing an app for mobile, performance is a real concern.

The approach I'm suggesting would instead have some kind of a `path` to the SQLite database optionally included in the `postMessage` and would automatically fetch it via GET, then convert it into an ArrayBuffer e.g:

worker.postMessage({
    id:1,
    action:'open',
    path:'/path/to/database.sqlite'
});

Could something like this be added to `worker.sql.js`? Or perhaps this is a separate concern and I should write my own Web Worker script? Going forward, I think this would be a help to a lot of people in the same situation as myself.

**Comment by jasdeepkhalsa** [comment]
I've managed to get something working! This is the main `app.js` file:

```javascript
if (!!window.Worker) {
    var worker = new Worker("worker.js");

    worker.postMessage({
        url: '/path/to/sqlite.db',
        sql: "SELECT * FROM table"
    });

    worker.onmessage = function(event) {
        console.log(event.data);
        worker.terminate();
    };

    worker.onerror = function(e) {console.log("Worker error: ", e)};
}
```

And `worker.js` which includes a path to the normal `sql.js` (NOT `worker.sql.js`):

```javascript
importScripts('sql.js');

onmessage = function(message){

	http(message.data.url,message.data.sql);

	function http(url, sql)
	{
		var url = url;
		var sql = sql;

		var xhr = new XMLHttpRequest();
		xhr.open('GET', url, true);
		xhr.responseType = 'arraybuffer';

		xhr.onload = function(e) {
		  postMessage(applyTransform(this.response, sql));
		  close();
		};

		xhr.send();
	}

	function applyTransform(result, sql)
	{
	    var data = [];
	    var uInt8Array = new Uint8Array(result);
	    var db = new SQL.Database(uInt8Array);
	    var stmt = db.prepare(sql);
	    while(stmt.step())
	    {
	        data.push(stmt.getAsObject())
	    }
	    db.close();
	    return data;
	}
}
```

This returns the data as a JSON array - since I'm consuming it in Angular.js :+1: 

Hope this is of help to someone :)

**Comment by lovasoa** [comment]
A postMessage with a whole db is not a performance concern: http://updates.html5rocks.com/2011/12/Transferable-Objects-Lightning-Fast

But I agree it would be handier if worker.sql.js could send the xmlhttprequest on its own. But that would mean adding browser-specific code to this project. Currently, all tests are run within node, which doesn't have the browser's xmlhttprequest interface...

**Comment by jasdeepkhalsa** [comment]
Thanks for the article @lovasoa ! I didn't know about Transferable Objects - that's pretty cool!
