### ISSUE TITLE
More Database.export flexibility

### ISSUE THREAD

**Issue by 3vangelist** [kripken/sql.js#86]
Great library, using this for a Phonegap project, but having to export database into memory and then write into FileEntry object of my choosing by re-encoding.

Could you introduce functionality to write straight to a FileEntry object? I know according to W3C its depecated, perhaps receiving a filename argument instead and using the build in FS object that your library uses instead?

**Comment by lovasoa** [comment]
What you call ["the built in FS object that your library uses"](https://github.com/kripken/sql.js/blob/master/coffee/api.coffee#L395) is [emscripten's filesystem API](http://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html). It does not have access to any physical filesystem by default.

And I don't think integrating plateform-specific stuffs in `sql.js` is a good idea.

But if you want to write an emscripten FS backend for phonegap, go ahead, you could use it in your application, and it would be useful to other people! But it's not straightforward.

**Comment by 3vangelist** [comment]
Thanks for the link, I'll check it out :)
