### ISSUE TITLE
Issues with DELETE FROM using prepared statement

### ISSUE THREAD

**Issue by 3vangelist** [kripken/sql.js#87]
Looks like DELETE using prepared args isn't working. Using the following code wrapper (ConkerDatabase.db is instance of SQL.Database). Steps all the way through and calls saveToDisk.
```
ConkerDatabase.prototype.performQuery = function(statement,args,saveToDisk)
{
	if(!args)	args={};
	if(typeof saveToDisk === 'undefined')	
		saveToDisk = true;
	this.records = [];
	this.errorInfo=false;
	this.statement=false;
	try
	{
		this.statement = this.db.prepare(statement,args);
	}
	catch(e)
	{
		this.errorInfo = e.message;
	}
	if(!this.errorInfo)
	{
		while(this.statement.step())
		{
			this.records.push(this.statement.getAsObject());
		}
		
		// If this wasn't a SELECT, it ws probably a change to the db - trigger a save.
		var hasModifiedData = Math.max(statement.search(/insert into/i),
									statement.search(/replace into/i),
									statement.search(/update/i),
									statement.search(/delete from/i)) == 0;
		if(hasModifiedData && saveToDisk)
			this.saveToDisk();
	}
	if(this.statement)
	{
		this.statement.free();
	}
}
```

Combined with the following query line (cdb is instance of ConkerDatabase):

```
cdb.performQuery("DELETE FROM `Schedule` WHERE `user_id` IN (:0)",{":0":"18223"}); 
```

No errors (caught or uncaught), records remain in the database. My wrapper works with all other types of statement (Create, Select, Replace etc)

**Comment by lovasoa** [comment]
The problem is in your code, not in `sql.js`. You bind a string instead of an integer.

Here is a working version: http://jsfiddle.net/2bx0ry5j/

Values have types in SQL, and in sqlite in particular. Please read the [documentation of sqlite about types](https://www.sqlite.org/datatype3.html).

More generally, when you think you found a bug in `sql.js`, please test your queries in a normal sqlite shell first.
```sql
sqlite> create table a(b);
sqlite> insert into a VALUES (1);
sqlite> select * from a where b="1";
sqlite> select * from a where b=1;
1
```

**Comment by 3vangelist** [comment]
Ok thanks, I'm used to working with PDO drivers in MySQL server-side, so presumed SQLite would evaluate '18223' to 18223. Thankyou for clarifying!
