### ISSUE TITLE
Spatialite support ?

### ISSUE THREAD

**Issue by glibersat** [kripken/sql.js#89]
Hi,

First of all, thank you for this awesome piece of code!
I was wondering how hard would it be to add spatialite support? Are you aware of any problem that would prevent it to be compiled?

Thank you,

Guillaume

**Comment by jvail** [comment]
Experimental, seems to work though: https://github.com/jvail/spatiasql.js

**Comment by lovasoa** [comment]
Wow, thank you very much for your work!

**Comment by jvail** [comment]
Well, many thanks for your work! Mine is sort of epigonal.

**Comment by dinedal** [comment]
Closing as resolved.
