### ISSUE TITLE
Uncaught Error: INDEX_SIZE_ERR: DOM  on Androïd

### ISSUE THREAD

**Issue by GCorbel** [kripken/sql.js#90]
I want to use SQLite on Android but I have this error : 

    Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1, http://192.168.1.104:8100/lib/sql.js, Line: 1051

I'm using ionic. Is there a solution?

**Comment by lovasoa** [comment]
Please give a simple way to reproduce the error and a full debug log. For error reporting please use a [debug version of the library](http://kripken.github.io/sql.js/js/sql-debug.js).

And are you sure that the error doesn't simply come from insufficient memory available on the device?

**Comment by GCorbel** [comment]
This is a memory problem. The simpler way to reproduce the bug is : 

    var TOTAL_MEMORY = 16777216;
    var buffer = new ArrayBuffer(TOTAL_MEMORY);
    HEAPF64 = new Float64Array(buffer);

If I understand, it looks like a memory problem but it works for other heaps. If I understand, I have to recompile with other memory settings. Is it right?

It still fail with `TOTAL_MEMORY = 8`.

**Comment by lovasoa** [comment]
Then it's not a bug in `sql.js`. You can recompile with a smaller memory array, but then you won't be able to open large databases. If you are creating a mobile application, maybe you should use one of the recommended ways to store your data. For cordova: http://cordova.apache.org/docs/en/4.0.0/cordova_storage_storage.md.html#Storage

**Comment by GCorbel** [comment]
It works with `HEAPF64 = new Float64Array(16777216);` but I don't know what can be consequences.

**Comment by lovasoa** [comment]
Are you editing the `sql.js` file directly? That's not a good idea. If you want to change sql.js, you should recompile it. The generated code may depend on the memory array size in several places.

**Comment by GCorbel** [comment]
I was just testing to understand. I think to recompile with less memory will not resolve the bug because it does not work when `TOTAL_MEMORY` is very small. I need to use a sqlite dabatase. If I don't find the solution with sql.js, I will find something else.
