### ISSUE TITLE
UPDATE , not working 

### ISSUE THREAD

**Issue by cukatch** [kripken/sql.js#94]
var stmt = db.prepare("UPDATE cpi_tcpis SET rationale=@rationale, state=@state WHERE wbsId=$key");
      stmt.bind({'@rationale':entry, '@state':'Saved', $key:key});
      stmt.step();

      console.log(stmt.getAsObject()); 

for reason i am repeatedly getting an empty object, am i doing some thing wrong?

**Comment by lovasoa** [comment]
Update does not return any data in sql.
Please check that all your queries run as you expect in sqlite before reporting issues.

**Comment by cukatch** [comment]
all of the other queries work , i just can't figure out Update. Do i need to use the .save method ?
