### ISSUE TITLE
Fail to run in a Chrome packaged app

### ISSUE THREAD

**Issue by luke8977ka** [kripken/sql.js#97]
I have the same problem with use of eval function when I packaged in Chrome App.
And I saw "Emscripten generated modules fail to run in a Chrome packaged app #2312" this issue.
Could you help me to generate sql.js without contentSecurityPolicy. Thanks.

**Comment by Duckbrain** [comment]
I have it running great in a Chrome App. You need to add `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';"` to your manifest.json file. This allows you to use `eval`. I've also found it's best, if possible, to lazy load it in the background page and let your app pages request it through Chrome's messaging API. This will save you a lot of memory.

**Comment by dinedal** [comment]
Thanks @duckbrain 

Closing this issue as solved.
