### ISSUE TITLE
can i use

### ISSUE THREAD

**Issue by wozzup** [kripken/sql.js#98]
can i use sql.js in html5 websql?
can i use sql.js in html5 indexeddb?
can i use sql.js in [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage)?

**Comment by lovasoa** [comment]
>can i use sql.js in html5 websql?
No
>can i use sql.js in html5 indexeddb?
No
>can i use sql.js in html5
>[Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage)?
No
>

But pull requests are welcome :)

**Comment by wozzup** [comment]
haha, thanks for the reply, lovasoa ;)

**Comment by ltearno** [comment]
I've used it many times inside a browser to have a cross browser compatible
sql stack.

Otherwise you have the lovesoa (if i remember well) project that is above
the different database browser implémentations.

I can provide you somme code on github if you are interested.

Thanks
Arnaud Tournier

**Comment by lovasoa** [comment]
I think the questions were about having `sql.js` save its database to indexeddb, or websql automatically.

The problem of `sql.js` in its current shape is that it doesn't automatically save its data anywhere. When the page is reloaded, the data is lost.

**Comment by wozzup** [comment]
Dear lovasoa,

the data save is client(browser) behavior. and indexeddb, websql is html5 feature: http://www.w3.org/TR/IndexedDB/

**Comment by lovasoa** [comment]
I know that. And?

**Comment by wozzup** [comment]
@lovasoa and, once the data insert or update or CRUD will be storage  in `window.openDatabase('documents...`, reload page data won't lose.

**Comment by lovasoa** [comment]
What I was saying is that currently, sql.js saves all its data in memory, and cannot use indexeddb (for instance) as a backend. The library user has to save the data to a persistent database manually.

Using another backend than memory would be a nice feature to have.

**Comment by wozzup** [comment]
@lovasoa ooops... dear lovasoa, sorry i missing the point, my bad. keep data in  memory is a excellent idea. awesome! have nice day ;)

**Comment by ltearno** [comment]
I usually use sql.js in the browser to have all the SQL functionnalities.
Whereas i store and save the data in the browser's local storage, encoding
the binary image of the database (the sqlite file in other words) in base64.

An example of that technique can be found here :
https://github.com/ltearno/OfflineDemo

The thing that is cool is that with this technique you cover all the
browsers and have a fully functional SQL database.

The downside is that you have to download the sql.js file on the browser,
which is kind of big. Yet, you can cache it indefinitely and still allow to
upgrade the sql.js version by using the perfect caching technique.

Thanks
Arnaud

**Comment by wozzup** [comment]
thank you Arnaud. the demo inspired me. works great!

**Comment by lovasoa** [comment]
I think that localStorage can store binary strings. So you don't need to convert your database to base64.

**Comment by ltearno** [comment]
At the time i did this application it was not possible (at least on all
browsers).

If that is possible now, that's great news because performances will be
better !

Thanks, i'll investigate soon
Arnuad

Le lun. 20 avr. 2015 à 11:23, Ophir LOJKINE <notifications@github.com> a
écrit :
