### ISSUE TITLE
i want to store my db file in a specified location given by me

### ISSUE THREAD

**Issue by naseerhussain** [kripken/sql.js#99]
sqljs is working fine but i want a way to specify the location of the db file and i should be able to use the same db by just opening it. how can i achieve this. help in this regard. i'm not using php/perl/python, i want to do it by javascript.

**Comment by lovasoa** [comment]
When you want help with your own code, please be polite. A little please wouldn't have been too much.

Do you want to save the db file to the server, or to the client?

- If you want to save it to the server, you will need server-side code (php/perl/python/whatever).

- If you want to save it to the client, it's not possible. At least, not directly. JS code in the browser cannot save a file wherever it wants in the client file system. It would be a security issue. You need to export the database as an UInt8Array, then create an object url, then create an <a> tag with a download attribute. The user will be able to choose where he wants to store the db file.

**Comment by naseerhussain** [comment]
sorry ,.. Actually i'm a beginner to the sqllite. I'm doing my development in ubuntu machine, i tried to configure the nodejs and sqlite for my project, but unfortunately not getting it. so i downloaded the sql.js file and included the sql.js file in my html ile and started using it directly in my code. Can u please send me a piece of code which explains everything like, 

> Creating database with desired name.

> Creating tables and inserting values to it.

> closing database file.

> Opening the same database file by giving the path of the file and fetch contents.
